version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: "harraga_db"
    volumes:
      - db_vol:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
    expose:
      - 3306
    ports:
      - "3306:3306"
  phpmyadmin:
    links:
      - db
    image: phpmyadmin/phpmyadmin
    expose:
      - '8081'
    ports:
      - "8081:8081"
    environment:
      PMA_HOST: db
      VIRTUAL_HOST: phpmyadmin.harraga.local
      MYSQL_ROOT_PASSWORD: root
  web:
    container_name: harraga_web
    build:
      context: .
    links:
      - db
    image: tomcat:9.0.48
    volumes:
      - ./target/harraga.war:/usr/local/tomcat/webapps/harraga.war
    expose:
      - '8080'
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  db_vol: